# Generated by Django 2.2 on 2019-10-23 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=920)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_received_quantity', models.IntegerField()),
                ('dispatch_received_date', models.DateField(default=django.utils.timezone.now)),
                ('dispatch_dispatch_quantity', models.IntegerField()),
                ('dispatch_balance_quantity', models.IntegerField()),
                ('dispatch_rejected_quantity', models.IntegerField()),
                ('dispatch_bill_number', models.IntegerField()),
                ('dispatch_bill_file', models.FileField(upload_to='')),
                ('dispatch_payment_status', models.CharField(max_length=920)),
                ('dispatch_order_date_of_entry', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Dispatch Order',
                'verbose_name_plural': 'Dispatch Orders List',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_order_number', models.CharField(max_length=920)),
                ('order_order_type', models.CharField(max_length=920)),
                ('order_order_brands', models.CharField(max_length=920)),
                ('order_order_style_number', models.CharField(max_length=920)),
                ('order_order_fit', models.CharField(max_length=920)),
                ('order_order_quantity', models.IntegerField()),
                ('order_order_date', models.DateField(default=django.utils.timezone.now)),
                ('order_delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('order_order_category', models.CharField(max_length=920)),
                ('order_fit_sample_status', models.CharField(max_length=920)),
                ('order_fit_sample_submitted_date', models.DateField(default=django.utils.timezone.now)),
                ('order_pps_sample_status', models.CharField(max_length=920)),
                ('order_pps_sample_submitted_date', models.DateField(default=django.utils.timezone.now)),
                ('order_order_remark', models.CharField(blank=True, max_length=920)),
                ('order_order_date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders List',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=920)),
                ('vendor_type', models.CharField(max_length=920)),
                ('vendor_balance_stock', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fabric_Order',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='KNGarment_Order_TrackPro_App.Process')),
                ('fabric_order_sort_number', models.CharField(max_length=920)),
                ('fabric_order_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fabric Order',
                'verbose_name_plural': 'Fabric Orders List',
            },
            bases=('KNGarment_Order_TrackPro_App.process',),
        ),
        migrations.CreateModel(
            name='Finishing',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='KNGarment_Order_TrackPro_App.Process')),
                ('finishing_rate', models.IntegerField()),
                ('finishing_delivery_quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Finishing Order',
                'verbose_name_plural': 'Finishing Orders List',
            },
            bases=('KNGarment_Order_TrackPro_App.process',),
        ),
        migrations.CreateModel(
            name='Stiching',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='KNGarment_Order_TrackPro_App.Process')),
                ('stiching_average_one', models.FloatField()),
                ('stiching_average_two', models.FloatField()),
                ('stiching_average_three', models.FloatField()),
                ('stiching_rate_one', models.FloatField()),
                ('stiching_rate_two', models.FloatField()),
                ('stiching_rate_three', models.FloatField()),
                ('stiching_opening_fabric_stock', models.IntegerField()),
                ('stiching_opening_stock_date', models.DateField(default=django.utils.timezone.now)),
                ('stiching_fabric_bill_date', models.DateField(default=django.utils.timezone.now)),
                ('stiching_fabric_used', models.CharField(max_length=920)),
            ],
            options={
                'verbose_name': 'Stiching Order',
                'verbose_name_plural': 'Stiching Orders List',
            },
            bases=('KNGarment_Order_TrackPro_App.process',),
        ),
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='KNGarment_Order_TrackPro_App.Process')),
                ('washing_process_name', models.CharField(max_length=920)),
                ('washing_rate', models.IntegerField()),
                ('washing_order_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Washing Order',
                'verbose_name_plural': 'Washing Orders List',
            },
            bases=('KNGarment_Order_TrackPro_App.process',),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_vendor_name', models.CharField(blank=True, max_length=920)),
                ('process_vendor_location', models.CharField(blank=True, max_length=920)),
                ('process_received_quantity', models.IntegerField(blank=True, null=True)),
                ('process_received_date', models.DateField(default=django.utils.timezone.now)),
                ('process_delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('process_bill_number', models.IntegerField(blank=True, null=True)),
                ('process_bill_file', models.FileField(blank=True, upload_to='')),
                ('process_payment_status', models.CharField(blank=True, max_length=920)),
                ('process_date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('process_order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Orders')),
                ('process_vendor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Vendor')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process List',
            },
        ),
    ]
