# Generated by Django 2.2 on 2019-10-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_bill_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
