# Generated by Django 2.2.5 on 2019-10-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=920)),
                ('vendor_type', models.CharField(max_length=920)),
                ('vendor_balance_stock', models.FloatField()),
            ],
        ),
    ]
