# Generated by Django 2.2 on 2019-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0002_auto_20191023_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='stiching',
            name='stiching_fabric_bill_number',
            field=models.CharField(blank=True, max_length=920),
        ),
    ]
