# Generated by Django 2.2.5 on 2019-10-30 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0003_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_vendor_name', models.CharField(blank=True, max_length=920)),
                ('process_vendor_location', models.CharField(blank=True, max_length=920)),
                ('process_received_quantity', models.IntegerField(blank=True, null=True)),
                ('process_received_date', models.DateField(default=django.utils.timezone.now)),
                ('process_delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('process_bill_number', models.IntegerField(blank=True, default=0)),
                ('process_bill_file', models.FileField(blank=True, upload_to='')),
                ('process_payment_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Paid'), (2, 'Pending')], default=2)),
                ('process_date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('process_order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Orders')),
                ('process_vendor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Vendor')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process List',
            },
        ),
    ]
