# Generated by Django 2.2 on 2019-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0003_stiching_stiching_fabric_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='washing',
            name='washing_delivery_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
