# Generated by Django 2.2.5 on 2019-10-24 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0004_washing_washing_delivery_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_order_date_of_entry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
