# Generated by Django 2.2.5 on 2019-10-25 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0005_auto_20191024_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Mens_Or_Ladies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_mens_or_ladies_size_26_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_28_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_30_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_32_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_34_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_36_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_38_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_40_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_42_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_size_44_quantity', models.CharField(blank=True, max_length=920)),
                ('order_mens_or_ladies_order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Orders')),
            ],
            options={
                'verbose_name': 'Mens Or Ladies Order',
                'verbose_name_plural': 'Mens Or Ladies Orders List',
            },
        ),
        migrations.CreateModel(
            name='Order_Kids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_kids_age_2_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_3to4_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_5to6_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_7to8_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_9to10_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_11to12_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_13to14_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_15to16_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_2to3_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_4to5_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_6to7_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_8to9_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_10to11_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Orders')),
            ],
            options={
                'verbose_name': 'Kids Order',
                'verbose_name_plural': 'Kids Orders List',
            },
        ),
        migrations.CreateModel(
            name='Order_Ethenic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ethenic_size_XS', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_S', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_M', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_L', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_XL', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_XXL', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_XXXL', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Orders')),
            ],
            options={
                'verbose_name': 'Ethenic Order',
                'verbose_name_plural': 'Ethenic Orders List',
            },
        ),
    ]
