# Generated by Django 2.2.5 on 2019-10-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0006_order_ethenic_order_kids_order_mens_or_ladies'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric_order',
            name='process_type',
            field=models.CharField(default='Fabric Order', max_length=920),
        ),
        migrations.AddField(
            model_name='finishing',
            name='process_type',
            field=models.CharField(default='Finishing', max_length=920),
        ),
        migrations.AddField(
            model_name='stiching',
            name='process_type',
            field=models.CharField(default='Stiching', max_length=920),
        ),
        migrations.AddField(
            model_name='washing',
            name='process_type',
            field=models.CharField(default='Washing', max_length=920),
        ),
    ]
