# Generated by Django 2.2.5 on 2019-10-31 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0006_fabric_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stiching',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='KNGarment_Order_TrackPro_App.Process')),
                ('process_type', models.PositiveSmallIntegerField(default=2)),
                ('stiching_average_one', models.FloatField()),
                ('stiching_average_two', models.FloatField()),
                ('stiching_average_three', models.FloatField()),
                ('stiching_rate_one', models.FloatField()),
                ('stiching_rate_two', models.FloatField()),
                ('stiching_rate_three', models.FloatField()),
                ('stiching_opening_fabric_stock', models.IntegerField()),
                ('stiching_opening_stock_date', models.DateField(default=django.utils.timezone.now)),
                ('stiching_fabric_bill_date', models.DateField(default=django.utils.timezone.now)),
                ('stiching_fabric_used', models.CharField(max_length=920)),
                ('stiching_fabric_bill_number', models.CharField(blank=True, max_length=920)),
            ],
            options={
                'verbose_name': 'Stiching Order',
                'verbose_name_plural': 'Stiching Orders List',
            },
            bases=('KNGarment_Order_TrackPro_App.process',),
        ),
    ]
