# Generated by Django 2.2.5 on 2019-10-30 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0006_stiching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='KNGarment_Order_TrackPro_App.Process')),
                ('process_type', models.PositiveSmallIntegerField(default=3)),
                ('washing_process_name', models.CharField(max_length=920)),
                ('washing_rate', models.IntegerField()),
                ('washing_order_date', models.DateField(default=django.utils.timezone.now)),
                ('washing_delivery_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Washing Order',
                'verbose_name_plural': 'Washing Orders List',
            },
            bases=('KNGarment_Order_TrackPro_App.process',),
        ),
    ]
