# Generated by Django 2.2.5 on 2019-10-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0007_auto_20191030_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric_order',
            name='process_type',
        ),
        migrations.RemoveField(
            model_name='finishing',
            name='process_type',
        ),
        migrations.RemoveField(
            model_name='stiching',
            name='process_type',
        ),
        migrations.RemoveField(
            model_name='washing',
            name='process_type',
        ),
    ]
