# Generated by Django 2.2.5 on 2019-10-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0008_auto_20191030_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_payment_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Paid'), (2, 'Pending')], default=2),
        ),
    ]
