# Generated by Django 2.2.5 on 2019-10-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0009_auto_20191030_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric_order',
            name='process_type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
