# Generated by Django 2.2.5 on 2019-10-31 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0009_finishing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_received_quantity', models.IntegerField()),
                ('dispatch_received_date', models.DateField(default=django.utils.timezone.now)),
                ('dispatch_dispatch_quantity', models.IntegerField()),
                ('dispatch_balance_quantity', models.IntegerField()),
                ('dispatch_rejected_quantity', models.IntegerField()),
                ('dispatch_bill_number', models.IntegerField()),
                ('dispatch_bill_file', models.FileField(upload_to='')),
                ('dispatch_payment_status', models.CharField(max_length=920)),
                ('dispatch_order_date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Dispatch Order',
                'verbose_name_plural': 'Dispatch Orders List',
            },
        ),
    ]
