# Generated by Django 2.2.5 on 2019-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0010_fabric_order_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishing',
            name='process_type',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='stiching',
            name='process_type',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='washing',
            name='process_type',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
