# Generated by Django 2.2.5 on 2019-10-31 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0011_order_mens_or_ladies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Kids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_kids_age_2_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_3to4_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_5to6_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_7to8_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_9to10_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_11to12_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_13to14_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_15to16_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_2to3_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_4to5_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_6to7_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_8to9_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_age_10to11_years', models.CharField(blank=True, max_length=920)),
                ('order_kids_order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Orders')),
            ],
            options={
                'verbose_name': 'Kids Order',
                'verbose_name_plural': 'Kids Orders List',
            },
        ),
    ]
