# Generated by Django 2.2.5 on 2019-10-31 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0012_order_kids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Ethenic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ethenic_size_XS', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_S', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_M', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_L', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_XL', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_XXL', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_size_XXXL', models.CharField(blank=True, max_length=920)),
                ('order_ethenic_order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='KNGarment_Order_TrackPro_App.Orders')),
            ],
            options={
                'verbose_name': 'Ethenic Order',
                'verbose_name_plural': 'Ethenic Orders List',
            },
        ),
    ]
