# Generated by Django 2.2.5 on 2019-11-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0014_auto_20191102_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fabric_vendor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='finishing_vendor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stitching_vendor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='washing_vendor',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'admin'), (1, 'super_admin'), (3, 'fabric_vendor'), (4, 'stitching_vendor'), (5, 'washing_vendor'), (6, 'finishing_vendor')], default=2),
        ),
    ]
