# Generated by Django 2.2.5 on 2019-11-06 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KNGarment_Order_TrackPro_App', '0015_auto_20191102_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_customuser_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(100, 'admin'), (108, 'super_admin'), (1, 'fabric_vendor'), (2, 'stitching_vendor'), (3, 'washing_vendor'), (4, 'finishing_vendor')], default=100),
        ),
    ]
